version: '3'
services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules:cached
  sb:
    image: logmh4gfdev_app:latest
    depends_on:
      - app
    tty: true
    working_dir: /app
    ports:
      - 6006:6006
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules:cached
    command: /bin/bash -c 'yarn && yarn storybook'

volumes:
  node_modules:
