name: "size limit"
on:
  pull_request:
jobs:
  size:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
