name: "size limit"
on:
  pull_request:
jobs:
  size:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    env:
      CI_JOB_NUMBER: 1
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
