name: todo-to-issue
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.6.3"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
